#!/usr/bin/env bash

# Generates the host-owned half of the node runtime environment.
#
# Everything written here is either a constant this repository already knows or
# a secret that never leaves this machine. The credentials shared with the
# control plane are not written here; the node fetches those itself over its
# authenticated channel and writes them to the delivered environment file.

set -euo pipefail

if [[ "$(id -u)" -ne 0 ]]; then
  echo "sulion-node-bootstrap must run as root" >&2
  exit 77
fi

bootstrap_file="${SULION_BOOTSTRAP_ENV_FILE:?missing SULION_BOOTSTRAP_ENV_FILE}"
delivered_file="${SULION_DELIVERED_ENV_FILE:?missing SULION_DELIVERED_ENV_FILE}"
token_file="${SULION_CODE_INTEL_TOKEN_FILE:?missing SULION_CODE_INTEL_TOKEN_FILE}"
release_repository="${SULION_RELEASE_REPOSITORY:?missing SULION_RELEASE_REPOSITORY}"
release_branch="${SULION_RELEASE_BRANCH:?missing SULION_RELEASE_BRANCH}"

# Activation owns these directories and their modes; the SSH key directory
# below the config path is deliberately group-readable, so do not restate
# ownership here.
for directory in "$(dirname "${bootstrap_file}")" "$(dirname "${delivered_file}")"; do
  if [[ ! -d "${directory}" ]]; then
    echo "expected activation to create ${directory}" >&2
    exit 72
  fi
done

# The node and code-intelligence containers talk over 127.0.0.1 on this host
# only, so their shared token is generated locally and never leaves the machine.
if [[ ! -s "${token_file}" ]]; then
  umask 077
  head -c 32 /dev/urandom | base64 | tr '+/' '-_' | tr -d '=\n' > "${token_file}"
  chmod 0600 "${token_file}"
  echo "generated a machine-local code intelligence token"
fi
code_intel_token="$(cat "${token_file}")"

# The release poller owns IMAGE_TAG once one is recorded. Only resolve the
# branch when this host has never deployed, so a bootstrap re-run cannot roll a
# pinned host forward on its own.
tag=""
if [[ -f "${bootstrap_file}" ]]; then
  tag="$(sed -n "s/^IMAGE_TAG=\([0-9a-f]\{40\}\)$/\1/p" "${bootstrap_file}")"
fi
if [[ -z "${tag}" ]]; then
  echo "resolving the current node release from ${release_branch}"
  tag="$(
    git ls-remote --exit-code "${release_repository}" "refs/heads/${release_branch}" |
      cut -f1
  )"
fi
if [[ ! "${tag}" =~ ^[0-9a-f]{40}$ ]]; then
  echo "${release_branch} did not resolve to one full Git commit SHA" >&2
  exit 65
fi

# An always-present delivered file keeps Compose's --env-file happy before the
# node has been approved for the first time.
if [[ ! -f "${delivered_file}" ]]; then
  umask 077
  echo "# Written by sulion-node after operator approval." > "${delivered_file}"
  chmod 0600 "${delivered_file}"
fi

candidate="$(mktemp "${bootstrap_file}.XXXXXX")"
trap 'rm -f "${candidate}"' EXIT
chmod 0600 "${candidate}"

cat > "${candidate}" <<EOF
# Generated by sulion-node-bootstrap. Do not edit.
# Shared credentials are not here: the node receives those over its
# authenticated control channel and writes ${delivered_file}.
IMAGE_TAG=${tag}
SULION_IMAGE_REGISTRY=${SULION_IMAGE_REGISTRY}
SULION_HOME_HOST_PATH=${SULION_HOME_HOST_PATH}
SULION_REPOS_HOST_PATH=${SULION_REPOS_HOST_PATH}
SULION_WORKSPACES_HOST_PATH=${SULION_WORKSPACES_HOST_PATH}
SULION_NODE_STATE_HOST_PATH=${SULION_NODE_STATE_HOST_PATH}
SULION_NODE_ID=${SULION_NODE_ID}
SULION_NODE_CONTROL_URL=${SULION_NODE_CONTROL_URL}
SULION_NODE_ALLOW_INSECURE_WS=${SULION_NODE_ALLOW_INSECURE_WS}
SULION_SECRET_BROKER_URL=${SULION_SECRET_BROKER_URL}
SULION_RETRIEVAL_URL=${SULION_RETRIEVAL_URL}
SULION_CODE_INTEL_URL=${SULION_CODE_INTEL_URL}
SULION_DEV_PORT_RANGE=${SULION_DEV_PORT_RANGE}
SULION_CODE_INTEL_TOKEN=${code_intel_token}
EOF

if [[ -f "${bootstrap_file}" ]] && cmp -s "${candidate}" "${bootstrap_file}"; then
  echo "node bootstrap environment is current at release ${tag}"
  exit 0
fi

install -m 0600 -o root -g root "${candidate}" "${bootstrap_file}"
echo "wrote node bootstrap environment at release ${tag}"
